#!/usr/bin/env sh

changed() {
    git diff --name-only HEAD@{1} HEAD | grep "^$1" >/dev/null 2>&1
}

BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m'

printf "${BLUE}🔍 pnpm-lock.yml 변경사항 확인 중...${NC}\n"

if changed "pnpm-lock.yml"; then
    printf "${GREEN}📦 pnpm-lock.yml이 변경되었습니다. 의존성을 최신 상태로 업데이트합니다.${NC}\n"
    pnpm install
fi

printf "${GREEN}🎉 모든 업데이트가 완료되었습니다 :)${NC}\n"

exit 0