#!/usr/bin/env sh

function changed {
    git diff --name-only HEAD@{1} HEAD | grep "^$1" >/dev/null 2>&1
}

echo 'pnpm-lock.yml 변경사항 확인 중...'

if changed "pnpm-lock.yml"; then
    echo "📦 pnpm-lock.yml이 변경되었습니다. 의존성을 최신 상태로 업데이트합니다."
    pnpm install
fi

echo '모든 업데이트가 완료되었습니다 :)'

echo '필요한 경우 pnpm prebuild를 실행하여 네이티브 코드를 생성할 수 있습니다.'

exit 0